const products=[
{name:"JAALI PERFORATED OVERSIZED HOODIE",price:7490,stock:42,status:"LIVE",img:"https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=400&q=80"},
{name:"VARANASI RELIEF HEAVYWEIGHT TEE",price:3890,stock:28,status:"LIVE",img:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=400&q=80"},
{name:"MUKHYADHARA STATEMENT PULLOVER",price:7990,stock:17,status:"LOW STOCK",img:"https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=400&q=80"},
{name:"CHANDERI GEOMETRIC HEAVY TEE",price:3990,stock:56,status:"LIVE",img:"https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=400&q=80"}];
const orders=[
["MS-1048","Arjun R.","₹7,490","PAID","PROCESSING"],["MS-1047","Kabir S.","₹3,890","PAID","SHIPPED"],["MS-1046","Aarav M.","₹7,990","COD","DELIVERED"],["MS-1045","Rohan D.","₹3,990","PAID","DELIVERED"]];
let current="overview";const app=document.getElementById("app");
function shell(title,sub,action=""){return `<div class="page"><div class="page-head"><div><span class="mono">${sub}</span><h1>${title}</h1></div>${action}</div>`}
function overview(){app.innerHTML=shell("Overview","MAINSTREAM / ATELIER CONTROL",'<button class="btn" onclick="showAddProduct()">+ ADD PRODUCT</button>')+`
<div class="grid4"><div class="stat"><span>TODAY'S SALES</span><b>₹48,760</b><small>↑ 18.4%</small></div><div class="stat"><span>ORDERS</span><b>24</b><small>↑ 6 today</small></div><div class="stat"><span>PRODUCTS</span><b>8</b><small>2 low stock</small></div><div class="stat"><span>CUSTOMERS</span><b>186</b><small>↑ 12 this week</small></div></div>
<div class="charts section"><div><div class="section-head"><h2>REVENUE / LAST 7 DAYS</h2><span class="mono">₹1.84L</span></div><div class="bars">${[45,65,52,78,62,92,74].map(x=>`<div class="bar" style="height:${x}%"></div>`).join("")}</div></div><div><div class="section-head"><h2>RECENT ACTIVITY</h2></div><div class="activity"><div><b>New order MS-1048</b><span>2 minutes ago · ₹7,490</span></div><div><b>Product stock updated</b><span>18 minutes ago · Jaali Hoodie</span></div><div><b>New customer registered</b><span>42 minutes ago</span></div><div><b>Review received</b><span>1 hour ago · 5 stars</span></div></div></div></div>
<div class="section"><div class="section-head"><h2>TOP PRODUCTS</h2><button class="btn dark" onclick="page('products')">MANAGE PRODUCTS</button></div>${products.slice(0,4).map(p=>`<div class="product-row"><img class="thumb" src="${p.img}"><div><strong>${p.name}</strong><small>${p.stock} units remaining</small></div><b>₹${p.price.toLocaleString("en-IN")}</b><span class="pill green">${p.status}</span><span>126 sold</span><span class="actions">•••</span></div>`).join("")}</div></div>`}
function productPage(){app.innerHTML=shell("Products","CATALOG / 8 PRODUCTS",'<button class="btn" onclick="showAddProduct()">+ ADD PRODUCT</button>')+`<div class="section"><div class="section-head"><h2>NEW DROP / BATCH 004</h2><span class="mono">8 PRODUCTS</span></div>${products.map((p,i)=>`<div class="product-row"><img class="thumb" src="${p.img}"><div><strong>${p.name}</strong><small>Sizes XS–XXL · 3 colours</small></div><b>₹${p.price.toLocaleString("en-IN")}</b><span class="pill ${p.stock<20?"":"green"}">${p.stock<20?"LOW STOCK":"LIVE"}</span><span>${p.stock} units</span><span class="actions"><button onclick="editProduct(${i})">EDIT</button> <button onclick="deleteProduct(${i})">DELETE</button></span></div>`).join("")}</div></div>`}
function orderPage(){app.innerHTML=shell("Orders","SALES / ORDER MANAGEMENT",'<button class="btn dark" onclick="toast(\'Order export prepared\')">EXPORT ORDERS</button>')+`<div class="section"><div class="section-head"><h2>RECENT ORDERS</h2><span class="mono">24 TOTAL</span></div><table class="table"><thead><tr><th>ORDER</th><th>CUSTOMER</th><th>AMOUNT</th><th>PAYMENT</th><th>STATUS</th></tr></thead><tbody>${orders.map(o=>`<tr><td>${o[0]}</td><td>${o[1]}</td><td>${o[2]}</td><td><span class="pill">${o[3]}</span></td><td><span class="pill green">${o[4]}</span></td></tr>`).join("")}</tbody></table></div></div>`}
function customerPage(){app.innerHTML=shell("Customers","CRM / CUSTOMER LIST",'<button class="btn dark" onclick="toast(\'Customer export prepared\')">EXPORT</button>')+`<div class="grid4"><div class="stat"><span>TOTAL</span><b>186</b></div><div class="stat"><span>NEW THIS WEEK</span><b>12</b></div><div class="stat"><span>REPEAT</span><b>41%</b></div><div class="stat"><span>AVG ORDER</span><b>₹5,940</b></div></div><div class="section"><table class="table"><tr><th>CUSTOMER</th><th>LOCATION</th><th>ORDERS</th><th>LTV</th><th>STATUS</th></tr>${["Kabir Singhania|Mumbai, IN|4|₹29,960","Aarav Mehta|Bengaluru, IN|3|₹15,870","Devansh Kulkarni|New Delhi, IN|2|₹11,880","Rohan Deshmukh|Hyderabad, IN|1|₹3,990"].map(x=>{let a=x.split("|");return `<tr><td>${a[0]}</td><td>${a[1]}</td><td>${a[2]}</td><td>${a[3]}</td><td><span class="pill green">ACTIVE</span></td></tr>`}).join("")}</table></div></div>`}
function reviewPage(){app.innerHTML=shell("Reviews","COMMUNITY / MODERATION",'<button class="btn dark" onclick="toast(\'Review settings opened\')">SETTINGS</button>')+`<div class="grid4"><div class="stat"><span>AVERAGE</span><b>4.9</b></div><div class="stat"><span>REVIEWS</span><b>184</b></div><div class="stat"><span>5 STAR</span><b>92%</b></div><div class="stat"><span>PENDING</span><b>3</b></div></div><div class="section">${["The drape and weight feel substantial, with a strong Indian identity.","The tonal relief is understated and the fabric feels structured.","The typography is restrained and the heavyweight construction feels premium."].map((x,i)=>`<div class="activity"><div><b>★★★★★ · ${["Kabir Singhania","Aarav Mehta","Devansh Kulkarni"][i]}</b><span>${x}</span><small class="green">VERIFIED BUYER · PUBLISHED</small></div></div>`).join("")}</div></div>`}
function contentPage(){app.innerHTML=shell("Content","STORE / CONTENT CONTROL")+`<div class="content-grid"><div class="content-card"><span class="mono">HOMEPAGE HERO</span><h3>Drop 004 / Autumn Winter 2026</h3><p style="color:#888">Hero image, headline and CTA shown on the storefront.</p><span class="toggle on"></span><button class="btn dark" onclick="toast('Hero editor opened')">EDIT CONTENT</button></div><div class="content-card"><span class="mono">ANNOUNCEMENT</span><h3>Free express shipping across India</h3><p style="color:#888">Top announcement bar message.</p><span class="toggle on"></span><button class="btn dark" onclick="toast('Announcement editor opened')">EDIT</button></div><div class="content-card"><span class="mono">NEWSLETTER</span><h3>Inner Circle</h3><p style="color:#888">Early access and subscriber offers.</p><span class="toggle on"></span><button class="btn dark" onclick="toast('Newsletter editor opened')">EDIT</button></div><div class="content-card"><span class="mono">SOCIAL GALLERY</span><h3>@MAINSTREAM.IN</h3><p style="color:#888">Manage the 4-image community grid.</p><span class="toggle on"></span><button class="btn dark" onclick="toast('Gallery editor opened')">MANAGE</button></div></div></div>`}
function settingsPage(){app.innerHTML=shell("Settings","ATELIER / STORE SETTINGS")+`<div class="content-grid"><div class="content-card"><h3>Store settings</h3><div class="form"><label>STORE NAME</label><input value="MAINSTREAM"><label>SUPPORT EMAIL</label><input value="concierge@mainstream.in"><label>SHIPPING MESSAGE</label><input value="FREE EXPRESS SHIPPING ACROSS INDIA ON ALL ORDERS"><button class="btn" onclick="toast('Settings saved')">SAVE CHANGES</button></div></div><div class="content-card"><h3>Checkout</h3><p style="color:#888">Configure payment and delivery options.</p><p>UPI <span class="toggle on"></span></p><p>Cards <span class="toggle on"></span></p><p>Cash on Delivery <span class="toggle on"></span></p><p>International shipping <span class="toggle"></span></p></div></div></div>`}
function page(p){current=p;document.querySelectorAll(".sidebar nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===p));({overview,products:productPage,orders:orderPage,customers:customerPage,reviews:reviewPage,content:contentPage,settings:settingsPage}[p]||overview)()}
function showAddProduct(edit=null){$("#modalBody").innerHTML=`<span class="mono">CATALOG / PRODUCT</span><h2>${edit===null?"ADD NEW PRODUCT":"EDIT PRODUCT"}</h2><div class="form"><label>PRODUCT NAME</label><input id="pn" value="${edit!==null?products[edit].name:""}"><label>PRICE</label><input id="pp" type="number" value="${edit!==null?products[edit].price:""}"><label>STOCK</label><input id="ps" type="number" value="${edit!==null?products[edit].stock:""}"><label>DESCRIPTION</label><textarea placeholder="Product description"></textarea><button class="btn" onclick="saveProduct(${edit===null?-1:edit})">SAVE PRODUCT</button></div>`;$("#modal").classList.add("show")}
function editProduct(i){showAddProduct(i)}function saveProduct(i){let p={name:$("#pn").value||"NEW PRODUCT",price:+$("#pp").value||0,stock:+$("#ps").value||0,status:"LIVE",img:"https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=400&q=80"};if(i<0)products.unshift(p);else products[i]={...products[i],...p};closeModal();page("products");toast("Product saved")}
function deleteProduct(i){if(confirm("Delete this product?")){products.splice(i,1);page("products");toast("Product deleted")}}
function closeModal(){$("#modal").classList.remove("show")}function toast(msg){let x=document.createElement("div");x.className="toast";x.textContent=msg;document.body.appendChild(x);setTimeout(()=>x.remove(),2200)}
document.querySelectorAll(".sidebar nav button").forEach(b=>b.onclick=()=>page(b.dataset.page));document.getElementById("menu").onclick=()=>document.querySelector(".sidebar").classList.toggle("show");page("overview");